### ISSUE TITLE
center-side is not centered if left-side is none and right-side is not none

### ISSUE THREAD

**Issue by slashformotion** [Pablo-Gonzalez-Calderon/chic-header-package#1]
MWE
```typ
#import "chic-hdr.typ": *

#show: chic.with(
  chic-header(
    center-side: "Chic-header example",
    right-side: chic-heading-name(),
  ),
)

= h1
#pagebreak()
== h1.1
#pagebreak()
```

Gives:
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/45801817/58d64f7e-3257-4f49-a049-1baf95089d66)

A workaround is to set `left-side` to `""` .

**Comment by Pablo-Gonzalez-Calderon** [comment]
Now the Issue should be solved (I've made a typo in the commit 😅). Thank you for telling me the bug ;)
