### ISSUE TITLE
[QUESTION] align header element using `horizon`

### ISSUE THREAD

**Issue by slashformotion** [Pablo-Gonzalez-Calderon/chic-header-package#3]
MWE:
```typ
#import "chic-hdr.typ": *
#set page()
#show: chic.with(
  chic-header(
    center-side: [a \ b\ c],
    right-side: chic-heading-name(),
  ),
)

= h1
#pagebreak()

== h1.1
#pagebreak()
```
right now header elements are not aligned vertically:
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/45801817/2f7598b7-c376-4c65-acaf-a2d54292c80f)

They could be by using `horizon` in the align calls in `chic-grid`.
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/45801817/423a64e5-bbcd-443c-a3a5-b908e07bf47b)

**Comment by Pablo-Gonzalez-Calderon** [comment]
Looks interesting. I've never thougth of that 🤔. Looks as a good feature to implement
